FROM node:22 AS build

WORKDIR /label-maker

COPY frontend/package.json package.json
COPY frontend/package-lock.json package-lock.json

RUN npm ci

COPY /frontend .

RUN npm run build

FROM nginx:alpine

WORKDIR /label-maker
COPY --from=build /label-maker/dist .
COPY frontend/nginx.conf /etc/nginx/nginx.conf
